#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/proscene.jar:$APPDIR/lib/LeapJava.jar:$APPDIR/lib/LeapMotionP5.jar:$APPDIR/lib/aparapi.jar:$APPDIR/lib/SchoolOfFish.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar:$APPDIR/lib/LeapMotionForProcessing.jar:$APPDIR/lib/LeapJava.jar:$APPDIR/lib/tritonus_share.jar:$APPDIR/lib/mp3spi1.9.4.jar:$APPDIR/lib/tritonus_aos.jar:$APPDIR/lib/jsminim.jar:$APPDIR/lib/minim.jar:$APPDIR/lib/jl1.0.jar" SchoolOfFish "$@"
